version: "3.7"

services:
  build-web:
    container_name: ${NAME}-build-web-${BRANCH}
    environment:
      BRANCH: ${BRANCH}
      BASE_API: /${BRANCH}/api
      PUBLIC_PATH: /${BRANCH}/
    build: ../web
    volumes:
      - web:/web/dist

  web:
    container_name: ${NAME}-web-${BRANCH}
    hostname: web-${BRANCH}
    networks:
      default:
        aliases:
          - web-${BRANCH}
    image: nginx:alpine
    restart: always
    expose:
      - 80
    environment:
      BRANCH: ${BRANCH}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./script/nginx.sh:/nginx.sh
      - web:/usr/share/nginx/web/${BRANCH}
      - type: bind
        source: ./logs/${BRANCH}/nginx
        target: /var/log/nginx
    command: ['sh', 'nginx.sh']
    depends_on:
      - build-web
      - server

  server:
    container_name: ${NAME}-server-${BRANCH}
    hostname: server-${BRANCH}
    networks:
      default:
        aliases:
          - server-${BRANCH}
    build: ../server
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:7000/${BRANCH}/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - 7000
    environment:
      BRANCH: ${BRANCH}
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST:
    volumes:
      - type: bind
        source: ./logs/${BRANCH}/server
        target: /root/logs

networks: 
  default:
    external:
      name: ${NAME}
    
volumes:
  web: